### PR TITLE
TS migration

### PR DESCRIPTION
**Pull request by ndelangen**
fixes: https://github.com/moroshko/shallow-equal/issues/13

migrated the codebase to typescript & overhauled the build tools to use pika

### CODE REVIEW

**Comment by TrySound** [comment]
#7 actually already done. We forgot to close the issue.

**Comment by ndelangen** [comment]
WDYT, could this be released as a new major?

**Comment by fivecar** [comment]
@ndelangen : thank you for all your work on this. I've forked the codebase, integrated your changes, updated the release mechanism and bundler, added tests as well as a generic `shallowEqual`, and have launched it as [shallow-equal-modern](https://github.com/fivecar/shallow-equal-modern).

**Comment by moroshko** [comment]
I'm sorry guys. I really struggle with time. If anyone in interested to continue maintaining this package, [please react out on Twitter](https://twitter.com/moroshko).

**Comment by ndelangen** [comment]
I don't think any code in storybook uses this, sorry, I'll close this PR to reduce noise.

**Comment by fivecar** [comment]
v3.0.0 of this package now supports Typescript. Thanks, @ndelangen, for starting us down this path. (Also now uses microbundle, FWIW).

**Pull request closed without merging**
